### ISSUE TITLE
td_upload doesn't follow apikey in Td object

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/RTD#7]
template embulk yaml file uses `apikey: {{ env.TD_API_KEY }}`.
Then, it always requires an environment variable instead of apikey in td object.

https://github.com/chezou/RTD/blob/a3a6bdd7daf4ca0d54eae96f84d82de9242d457f/inst/extdata/tsv_upload.yml.liquid#L6

When I want to use it like this, it doesn't work well.

```
client <- Td(apikey="xx/xxxxxxx", endpoint="api.treasuredata.com")
```

**Comment by chezou** [comment]
@toru-takahashi Thanks for your report. RTD should ensure setting TD_API_KEY in this line https://github.com/chezou/RTD/blob/master/R/td.R#L72 for embulk.

**Comment by toru-takahashi** [comment]
Thank you!
